### ISSUE TITLE
Clicking on profiles causes Discord to crash

### ISSUE THREAD

**Issue by TheGreatTaz** [doggybootsy/BDPlugins#10]
reopening because this issue is still prevalent on v1.0.1

_Originally posted by @TheGreatTaz in https://github.com/doggybootsy/BDPlugins/issues/9#issuecomment-2081741494_

**Comment by TheGreatTaz** [comment]
i can provide more data if needed just let me know what

**Comment by doggybootsy** [comment]
Can you upload the error msg. And can you state what version of discord you use

**Comment by doggybootsy** [comment]
Hopefully this is resolved in the latest push. I did even more error protection

**Comment by TheGreatTaz** [comment]
from what i can tell your error protection worked
