### ISSUE TITLE
Friends Since - Not seeing it anywhere

### ISSUE THREAD

**Issue by kenjibailly** [doggybootsy/BDPlugins#12]
I tried to look where to find the feature after installing it. But I can't find it anywhere.
I have refreshed my discord client, but the feature isn't being visible in the user (mini) profile, nor in the full profile. 
I wonder where it can be found.

**Comment by doggybootsy** [comment]
Discord mightve broke the plugin

**Comment by doggybootsy** [comment]
Pushed a fix. Should fix this

**Comment by kenjibailly** [comment]
Yes it's working, thank you!!!!
