### ISSUE TITLE
[FriendIcon] Downlading to wrong location & not stopping properly

### ISSUE THREAD

**Issue by Strencher** [doggybootsy/BDPlugins#3]
I think it should be `__filename` instead as this leads you to the current plugins's filepath, meaning it can properly override.
Another issue is that the `updater` itself has no stop implementation, meaning it'll overlap.
https://github.com/doggybootsy/BDPlugins/blob/4641ac2029f66c5eb236493b7e96546199693cf1/friendIcon/friendIcon.plugin.js#L51

**Comment by doggybootsy** [comment]
fixed this too
