### ISSUE TITLE
Remove No Role not working anymore

### ISSUE THREAD

**Issue by Solomag** [doggybootsy/BDPlugins#4]
![изображение_2022-08-31_073616198](https://user-images.githubusercontent.com/33348398/187600154-82a1a96b-26fb-48a9-8205-68737619d659.png)

Screenshot while plugin is on

**Comment by Solomag** [comment]
For some reason it works on some servers. Some don't.

**Comment by doggybootsy** [comment]
Hm ill check it out

**Comment by doggybootsy** [comment]
fix in https://github.com/doggybootsy/BDPlugins/commit/e806bac674e52ff1a1948eb7085b975619927bfb
